---
  - name: Install epel-release
    yum:
      name: epel-release
      state: present

  - name: Install desktop
    yum:
      name: "{{ packages }}"
      state: present
    register: desktop
    changed_when: desktop.rc == 0
    failed_when: desktop.rc != 1 and desktop.rc != 0

  - name: Get default runlevel
    command: systemctl get-default
    register: runlevel
    changed_when: false

  - name: Set graphical runlevel
    command: systemctl set-default graphical.target
    when: runlevel.stdout != "graphical.target"

  - name: Is graphical currently active
    command: systemctl is-active graphical.target
    register: graphical
    failed_when: graphical.rc != 3 and graphical.rc != 0
    changed_when: false

  - name: Switch to graphical runlevel
    command: systemctl isolate graphical.target
    when: graphical.stdout != "active"

  - name: Enable autologin
    template:
      src: gdm.custom.conf.j2
      dest: /etc/gdm/custom.conf
      mode: '0544'
    notify: "restart gdm"
    when:
      - autologin_user is defined
      
  - name: Create backgrounds folder
    file:
      path: /usr/share/backgrounds/images
      state: directory
      mode: '0755'

  - name: Set background
    copy:
      src: wallpaper.jpg
      dest: /usr/share/backgrounds/images/default.png
      mode: '0644'
    notify: "restart gdm"

  - name: Use default panel
    copy:
      src: /etc/xdg/xfce4/panel/default.xml
      dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
      remote_src: yes
      mode: '0644'
    notify: "restart gdm"
...